class Solution {
    public int titleToNumber(String columnTitle) {
        // Initialize the output result...
        int output = 0;
        // Traverse the whole list through the loop...
        for(int i = 0; i < columnTitle.length(); i++){
            // Process to get the excel sheet column number...
            output = output * 26 + (columnTitle.charAt(i) - 'A' + 1);
        }
        return output;      // Return the output...
    }
}
